### ISSUE TITLE
Perfs

### ISSUE THREAD

**Issue by Solido** [lesnitsky/flutter_localstorage#1]
Can you publish some perfs on R/W please ?
Thanks you.

**Comment by lesnitsky** [comment]
@Solido Thanks for opening this up. Will do

**Comment by oakromulo** [comment]
@lesnitsky: I could add some flutter test drive testing batches with R/W performance evaluation.

**Comment by lesnitsky** [comment]
@oakromulo it would be awesome, go ahead!

**Comment by oakromulo** [comment]
@lesnitsky @Solido
PR https://github.com/lesnitsky/flutter_localstorage/pull/19 covers this issue https://github.com/lesnitsky/flutter_localstorage/issues/1
