### ISSUE TITLE
Persistent between runs?

### ISSUE THREAD

**Issue by mk0y** [lesnitsky/flutter_localstorage#10]
Nice plugin! Is there a way to persist data between runs in development phase (debug mode)?

Right now each time I run the app local storage is empty.

**Comment by lesnitsky** [comment]
@markzero do you have empty storage after app livereload? Or do you mean complete reinstall?

**Comment by mk0y** [comment]
When I re-run the app. Using `flutter run`. 
I guess storage is persisted while the app runs?

**Comment by lesnitsky** [comment]
This is weird, because I don't see storage being erased between flutter
runs... What emulator are you using?

**Comment by mk0y** [comment]
I'm using both Simulator for iOS and Android simulator. 

I tried with simple code:
```
@override
  void initState() {
    super.initState();
    Map<String, dynamic> data = _localStorage.getItem('items');
    debugger();
    _localStorage.ready.then((isReady) {
      if (isReady) {
        _localStorage.setItem('items', [1,2,3]);
      }
    });
  }
```

But every time data is empty (null).

**Comment by mk0y** [comment]
Sorry it should be `List<int>` but still, it works while app is running, for example between switching tabs etc, but when I re-run the app it starts with null, ie first call to getItem returns null.

**Comment by lesnitsky** [comment]
@markzero you should wait for `ready` in order to get data
I recommend using `FutureBuilder`

```dart
class SomeWidget extends StatelessWidget {
    final LocalStorage storage = new LocalStorage('my-name');

    @override
    Widget build(BuildContext context) {
        return FutureBuilder(
            future: storage.ready,
            builder: (BuildContext context, AsyncSnapshot snapshot) {
                  if (snapshot.hasData) {
                      // localstorage is ready
                      return MyPage(storage: strorage);
                  } else {
                      return CircularLoadingIndicator();
                  }
            }
        );
    }
}
```

**Comment by lesnitsky** [comment]
@markzero let me know if this example works for you

**Comment by mk0y** [comment]
@lesnitsky I don't have `hasData` but just `data` and it is just `AsyncSnapshot<bool>(ConnectionState.done, true, null)`.
There is no data that I set earlier (in initState for example).

I'm using `localstorage: ^1.2.0`.

You have data even when you re-run the app?

**Comment by mk0y** [comment]
Upgraded Flutter, seems it works now. When re-run the app there is state persistent now, not sure what was the case...
