### ISSUE TITLE
FileSystemException: An async operation is currently pending

### ISSUE THREAD

**Issue by lurongshuang** [lesnitsky/flutter_localstorage#101]
FileSystemException: An async operation is currently pending, path = '/var/mobile/Containers/Data/Application/748AAD7F-7060-4E93-8E22-A899249CE487/Documents/account_level_5184182830088322.json'

localstorage: ^4.0.1+4

**Comment by lurongshuang** [comment]
@lesnitsky Can you help me take a look

**Comment by Vollinator** [comment]
@lurongshuang 
Try to use "await" when calling "setItem" like this:

`await store.setItem(......);
`

**Comment by felix-mittermeier** [comment]
@lurongshuang Just using await inside the app is often not reliable in case of multiple parallel processes. I created a fork of this package and added the mutex (lock functionality) directly inside the code. Just switch to this modified version without any further code changes and the error is gone :-)

https://github.com/Ocell-io/flutter_localstorage

**Comment by brenomenosso** [comment]
@felix-mittermeier help me ?
