### ISSUE TITLE
delete item from local storage

### ISSUE THREAD

**Issue by Rajesh-Konki** [lesnitsky/flutter_localstorage#23]

**Comment by lesnitsky** [comment]
@Rajesh-Konki what is the issue? There is a [deleteItem](https://pub.dev/documentation/localstorage/latest/localstorage/LocalStorage/deleteItem.html) method. Are you experiencing any issues with it?

**Comment by lesnitsky** [comment]
@Rajesh-Konki closing this for now, let me know if you still have any issues with `deleteItem` method
