### ISSUE TITLE
Is this package different from shared_preferences?

### ISSUE THREAD

**Issue by rommyarb** [lesnitsky/flutter_localstorage#24]
Is this different from Shared Preferences. And which one is better for a simple app project?
Thank you!

**Comment by lesnitsky** [comment]
Yes, this is different
SharedPreferences use UserDefaults on ios and SharedPreferences android, which are system-level available storages. This is, on the other hand, is a plain json file storage, which makes it easier to debug the app during development (you can edit data directly)

**Comment by rommyarb** [comment]
> Yes, this is different
> SharedPreferences use UserDefaults on ios and SharedPreferences android, which are system-level available storages. This is, on the other hand, is a plain json file storage, which makes it easier to debug the app during development (you can edit data directly)

Thank you for the explanation! ❤️️

**Comment by lesnitsky** [comment]
you are very welcome
