### ISSUE TITLE
Support for Flutter Web

### ISSUE THREAD

**Issue by rodydavis** [lesnitsky/flutter_localstorage#25]
- You can use the localstorage that browsers provide for keyvalue store

**Comment by lesnitsky** [comment]
@AppleEducate this was on my todolist, just didn't have a chance to implement it yet

**Comment by rodydavis** [comment]
No worries, I will make a PR if I have time soon 😎

**Comment by rodydavis** [comment]
PR for the fix: https://github.com/lesnitsky/flutter_localstorage/pull/27

**Comment by rodydavis** [comment]
@lesnitsky let me know what you think!

**Comment by lesnitsky** [comment]
@AppleEducate great work! Thank you!

**Comment by rodydavis** [comment]
Sure thing!
