### ISSUE TITLE
Flushing of setItem

### ISSUE THREAD

**Issue by abacaj** [lesnitsky/flutter_localstorage#26]
Hi,

in `attemptFlush` should we be passing boolean true to flush call here:
`await _file.writeAsString(serialized);`
`await _file.writeAsString(serialized, flush: true);`

Not flushing can have negative side effect of trying to read (after a large write operation) before it is in file system.

**Comment by abacaj** [comment]
Also curious, what is the purpose of `readTest` in throughput measurement?

It is just reading from memory... it will be as fast as the platform allows it to be - which is unrelated to the library. The `writeTest` makes more sense since that does have some logic for encoding.

**Comment by oakromulo** [comment]
@abacaj the read test is there mostly for two reasons:
- for fun
- to make it explicit that the whole thing is cached

> Also curious, what is the purpose of `readTest` in throughput measurement?

**Comment by oakromulo** [comment]
@abacaj just tackled it for proposed `v2.0.1` in the following PR:
https://github.com/lesnitsky/flutter_localstorage/pull/29/commits/49614e98d74cf03732a1580ccbe05d244b3b7765

> in `attemptFlush` should we be passing boolean true to flush call here:
> `await _file.writeAsString(serialized);`
> `await _file.writeAsString(serialized, flush: true);`

@lesnitsky: this one is pretty important, @abacaj is absolutely right

**Comment by oakromulo** [comment]
@abacaj just tackled it for proposed `v2.0.1` on commit https://github.com/lesnitsky/flutter_localstorage/pull/29/commits/49614e98d74cf03732a1580ccbe05d244b3b7765

> in `attemptFlush` should we be passing boolean true to flush call here:
> `await _file.writeAsString(serialized);`
> `await _file.writeAsString(serialized, flush: true);`

@lesnitsky: this one is pretty important, @abacaj is absolutely right

**Comment by oakromulo** [comment]
@abacaj just tackled it for proposed `v2.0.1` on commit https://github.com/lesnitsky/flutter_localstorage/pull/29/commits/49614e98d74cf03732a1580ccbe05d244b3b7765

@lesnitsky: this one is pretty important, @abacaj is absolutely right

> in `attemptFlush` should we be passing boolean true to flush call here:
> `await _file.writeAsString(serialized);`
> `await _file.writeAsString(serialized, flush: true);`

**Comment by lesnitsky** [comment]
closed by 876b8e6c8c0890cd96d20b35e7bec0ff51ccd8eb
