### ISSUE TITLE
setitem removes data

### ISSUE THREAD

**Issue by simphiwehlabisa** [lesnitsky/flutter_localstorage#28]
i have a list of json objects in my cart when i call set item on my cart it doesnt push new obects into my list of cart products ir removes it

**Comment by lesnitsky** [comment]
@simphiwehlabisa could you please provide a code example?

**Comment by lesnitsky** [comment]
@simphiwehlabisa any updates?

**Comment by simphiwehlabisa** [comment]
sorry @lesnitsky i figured it out i managed to edit the package works fine now thanks alot
