### ISSUE TITLE
No loaded items after updating to 3.0

### ISSUE THREAD

**Issue by nohli** [lesnitsky/flutter_localstorage#30]
Thanks for this package, I really like localstorage and never had issues before.

After updating to 3.0.0+2 my app did not load any items with the following code:

`final LocalStorage storage = LocalStorage('filename');
`

```
  Widget build(BuildContext context) => FutureBuilder(
        future: storage.ready,
        builder: (BuildContext context, snapshot) {
          if (snapshot.hasData) {
            storage.getItem('listname');
            ...
```

Does loading have to be async now - and how do I implement it?

**Comment by lesnitsky** [comment]
@nohli are you using this plugin on desktop or mobile?

**Comment by nohli** [comment]
On mobile, only tried on iOS 13.1.3 actually.

Latest Flutter stable.

**Comment by lesnitsky** [comment]
Do you mean that you can't get items after successful `setItem`, app reload
or after upgrading to v3? (meaning v2 worked fine, you had some data on
device, but can't retrieve this data using v3)

**Comment by nohli** [comment]
Latter

I downgraded to 2.0.0 and it loaded the lists.
Upgraded again and it didn‘t load.

**Comment by lesnitsky** [comment]
Ok, I will investigate
However major version bump (2 -> 3) usually implies _breaking_ change

**Comment by nohli** [comment]
Yeah of course, just wanted to let you know.
(the readme says breaking change for desktop only)

Maybe there is an option for my users not to lose all their data and updating.

I‘m really fine with 2.0 which works great.

Thanks for the plugin and replying!

**Comment by tehort** [comment]
I also have the same problem, iOS 13.2, had to roll-back to version 2.0.0
Doesn`t happen with Android and 3.0.0

**Comment by nohli** [comment]
Any news?

It seems like you've changed the path or something.

If I upgrade, the old lists are gone. I can save new lists.
If I then downgrade, the new lists are gone, and the old lists appear.
So I have two localstorages, depending on the version (2 or 3).

Any chance to easily migrate through your package?

**Comment by lesnitsky** [comment]
@nohli I found the root cause, v3.0 doesn't add `.json` extension, so if you want to use data saved using v2 you need to add `.json` extension on your own

so if v2 code was `final storage = new LocalStorage('my_data')`
v3 equivalent would be `new LocalStorage('my_data.json')`

I'm adding this to readme

**Comment by lesnitsky** [comment]
@nohli https://github.com/lesnitsky/flutter_localstorage#v2---v3-migration

**Comment by nohli** [comment]
That's great, thanks!!
Easy fix :)
