### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by bluemix** [lesnitsky/flutter_localstorage#31]
I hope there will be support for Windows.
Thanks for the effort and the library.

**Comment by lesnitsky** [comment]
@bluemix have you tried this package on windows?

**Comment by bluemix** [comment]
@lesnitsky , I didn't, because there is no Wndows folder in the project, and till date, I didn't find a project that uses a storage on Windows for Flutter. See [this issue](https://github.com/google/flutter-desktop-embedding/issues/434) for more info.

**Comment by lesnitsky** [comment]
this package will work as soon as `path_provider` implementation will be available on windows. Closing because it has nothing to do with `local_storage` package but rather `path_provider`

**Comment by lesnitsky** [comment]
See [google/flutter-desktop-embedding](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins/path_provider_fde) for more details

**Comment by lesnitsky** [comment]
@bluemix and btw you shared an issue which is related to `shared_preferences`. localstorage doesn't use `shared_preferences` under the hood

**Comment by bluemix** [comment]
Please clarify this in the package description.
when I saw, 
> 📦flutter localstorage for ios/android/desktop/web

I thought Windows is also included in the desktop environment.

**Comment by lesnitsky** [comment]
Yes, worth adding this note. I thought path provider is also available on
windows/linux, I was wrong
