### ISSUE TITLE
Support for non-json data?

### ISSUE THREAD

**Issue by TannerYoung** [lesnitsky/flutter_localstorage#35]
Is there any reason not to support just raw binary data?

I'd appreciate the flexibility of just being able to write/read a raw binary array (List<int>) to disk, and it would hardly even clutter the api (either an optional parameter on the setItem similiar to toEncodable or another function?).

Seems like this is intentionally out of scope, but there doesn't even seem to be a way to extend the library / re-use excellent components of it.

This is also the only file writing library that appears to work for ios, android, and web, which is why I want to use it.

**Comment by lesnitsky** [comment]
The idea behind this package is compatibility with web API (assuming web dev coming to flutter eco will search from familiar localstorage impl). Web LocalStorage can store only strings, but you can use [base 64](https://api.flutter.dev/flutter/dart-convert/base64-constant.html) to store binary data (base64 is a string representation of binary data)
