### ISSUE TITLE
Error in init silently fails

### ISSUE THREAD

**Issue by Ragnaroek** [lesnitsky/flutter_localstorage#36]
Took me a while to figure out what the problem was. At the end it was totally my fault, but maybe the error handling could be improved.

The PlatformNotSupportedError from io.dart/_getDocumentDir is thrown if you init the storage outside runApp

```
Future<Directory>` _getDocumentDir() async {
    print("_getDocumentDir");
    try {
      return await getApplicationDocumentsDirectory();
    } catch (err) {
      print("platform not supported: $err");
      throw PlatformNotSupportedError();
    }
  }
```

main function:

```
void main() {
  WidgetsFlutterBinding.ensureInitialized(); //<-- without this the PlatformNotSupportedError is throw
  final LocalStorage storage = new LocalStorage('app_data');
  storage.ready.then((ready) {
    if (ready) {
      runApp(TDMApp(storage: storage));
    }
  });
}
```

However the console does not print the error. The error message was super helpful in figuring out what the problem was.

Maybe there is no good way to support this better and misused it. Feel free to close the issue in this case.

**Comment by qieting** [comment]
> 花了我一段时间找出问题所在。最后，这完全是我的错，但是也许可以改善错误处理。
> 
> 如果您在runApp外部初始化存储，则会引发io.dart / _getDocumentDir中的PlatformNotSupportedError
> 
> ```
> Future<Directory>` _getDocumentDir() async {
>     print("_getDocumentDir");
>     try {
>       return await getApplicationDocumentsDirectory();
>     } catch (err) {
>       print("platform not supported: $err");
>       throw PlatformNotSupportedError();
>     }
>   }
> ```
> 
> 主功能：
> 
> ```
> void main() {
>   WidgetsFlutterBinding.ensureInitialized(); //<-- without this the PlatformNotSupportedError is throw
>   final LocalStorage storage = new LocalStorage('app_data');
>   storage.ready.then((ready) {
>     if (ready) {
>       runApp(TDMApp(storage: storage));
>     }
>   });
> }
> ```
> 
> 但是，控制台不会显示错误。该错误消息对于找出问题所在非常有帮助。
> 
> 也许没有更好的方法来更好地支持和滥用它。在这种情况下，请随时解决此问题。

I also encountered this problem, then how to solve it

**Comment by shangyilim** [comment]
> I also encountered this problem, then how to solve it

add 
```
WidgetsFlutterBinding.ensureInitialized(); 
```
before initializing LocalStorage fixed it for me

**Comment by qieting** [comment]
> > 我也遇到了这个问题，那怎么解决
> 
> 加
> 
> ```
> WidgetsFlutterBinding.ensureInitialized(); 
> ```
> 
> 在初始化LocalStorage之前为我修复了它

it is useful  thanks

**Comment by lesnitsky** [comment]
general note: this issue indicates you're trying to create an instance of localstorage outside of the widget tree, please avoid doing so. I recommend creating instances of localstorage inside `initState` of any stateful widget
