### ISSUE TITLE
Data doesn't persist in latest version, does in 2.0.0 (android)

### ISSUE THREAD

**Issue by nicoroy2561** [lesnitsky/flutter_localstorage#37]
Hi, I've been using this package but somehow with version 3.0.4 data wouldn't persist.
here's my code:

```
final storage = LocalStorage('my_data.dart');
 
await storage.ready.then((_) => {myVar = storage.getItem("myVar")});

//if myVar is null I set it here~
```

tried running on my android 10 phone, data wouldn't persist, even if I installed the app.
Tried changing my_data.dart to only my_data or anything else, wouldn't work as well. No error/exception was thrown either.
On a whim I thought I'd try to update the pubspec and set the package's version to 2.0.0, that worked. Now the data is persisting between hot reloads as it should.

**Comment by lesnitsky** [comment]
@nicoroy2561 can you try to run https://github.com/lesnitsky/flutter_localstorage/tree/master/example on your device and let me know if it works?

**Comment by nicoroy2561** [comment]
Not sure I did this right, I downloaded the whole git folder and tried to run it, this is the output I got:

`Launching lib/main.dart on Mi 9T in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Checking the license for package Android SDK Build-Tools 27.0.3 in /Users/[redacted]/Library/Android/sdk/licenses
License for package Android SDK Build-Tools 27.0.3 accepted.            
Preparing "Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)".  
"Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)" ready.      
Installing Android SDK Build-Tools 27.0.3 in /Users/[redacted]/Library/Android/sdk/build-tools/27.0.3
"Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)" complete.   
"Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)" finished.   
/Users/[redacted]/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/c3442e3e27884e7630b3c2089605bd2b/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
/Users/[redacted]/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/c3442e3e27884e7630b3c2089605bd2b/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugResources'.                 
> Failed to process resources, see aapt output above for details.       
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 16s                                                  
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        79.4s
AndroidX incompatibilities may have caused this build to fail. Please migrate your app to AndroidX. See https://goo.gl/CP92wY.
Gradle task assembleDebug failed with exit code 1`

**Comment by nicoroy2561** [comment]
Tried running it, I get this: 

Launching lib/main.dart on Mi 9T in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Invalid depfile: /Users/Roy/go/src/github.com/nicoroy2561/DM/demo_test/.dart_tool/flutter_build/b2f9474d2899a3d8e941253accdad8a9/kernel_snapshot.d
Invalid depfile: /Users/Roy/go/src/github.com/nicoroy2561/DM/demo_test/.dart_tool/flutter_build/b2f9474d2899a3d8e941253accdad8a9/kernel_snapshot.d
/Users/Roy/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/c3442e3e27884e7630b3c2089605bd2b/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
/Users/Roy/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/c3442e3e27884e7630b3c2089605bd2b/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugResources'.                 
> Failed to process resources, see aapt output above for details.       
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 30s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        32.4s
AndroidX incompatibilities may have caused this build to fail. Please migrate your app to AndroidX. See https://goo.gl/CP92wY.
Gradle task assembleDebug failed with exit code 1

**Comment by nicoroy2561** [comment]
I tried upgrading again to 3.0.0 (in my app) and it seems to work now. Did you change something?
I'll let you know if it stops working again or anything.

**Comment by nicoroy2561** [comment]
I tried again with 3.0.0, data persists only while the app is open - upon restarting nothing that was set last time stays. rolling back again to earlier version.
If you can help me understand how to properly set up the new version's example I will try it out.

**Comment by lesnitsky** [comment]
@nicoroy2561 I've checked out example both on android emulator and real device (Pixel 4XL) and it works fine... Could you please extract your code into small example project which demonstrates this issue?

**Comment by lesnitsky** [comment]
@nicoroy2561 fyi: I've recreated example app, check it out on your emulator/device

**Comment by Maclaon** [comment]
same issue! is it solved?

**Comment by dupiesdupreez** [comment]
This has not yet been solved

**Comment by lesnitsky** [comment]
@Maclaon @dupiesdupreez I'd be happy to solve this if I would have been able to reproduce this... Could someone create a reproducible example/share a complete code example that doesn't work?

**Comment by lesnitsky** [comment]
@nicoroy2561 

> somehow with version 3.0.4

Not sure how this is possible, the latest published version is v3.0.2

**Comment by nicoroy2561** [comment]
I'm currently testing it. After running into the same problem again, I found a solution here:
https://stackoverflow.com/questions/61436827/error-on-fluttersdkpath-packages-flutter-tools-gradle-app-plugin-loader-gradle
which finally gets the build to pass on my device.

The example app works on my device. Will take a look and see what might be the cause of it not working on my app

**Comment by nicoroy2561** [comment]
I tried changing your app around a bit, even having it point to version 3.0.0 (and not the rep's one directly) and it works.
Which means that something is going wrong with the app I'm developing. 
I say that data isn't persisting because upon hot reload my app (which is configured to download data from a server only if not present on the device) keeps re-downloading it all. Which might be one of two things: either the data isn't saved on the device correctly (my first thought) or the newer version of the plugin takes significantly more time to initialize than version 2.0.0 (and returns null in the mean time?). Which might explain why on a hot reload my app isn't able to retrieve the data it needs. 
Could it also be because I am not instantiating the storage item on the main.dart file, but rather a file called by another file called by that file? (still it doesn't make sense that version 2.0.0 works and 3.0.0 doesn't.)

**Comment by lesnitsky** [comment]
@nicoroy2561 it would be great if you can provide a code snippet/demo app which demonstrates the issue

**Comment by nicoroy2561** [comment]
@lesnitsky I know, and I wish I could. The problem is my app is fairly complex, so rearranging it into a "sample app" isn't feasible without a considerable amount of work. 
I can explain what it does with the plugin tho, and that might be useful. Maybe @Maclaon or someone else can provide a (non)working demo app.

Basically what my app does is it connects via websockets (within a file called ws.dart) to my server, and logs the user in.

That file imports data.dart, which contains
final storage = LocalStorage('app_name.json');
(I tried adding new in front, removing the .json and all a bunch of other stuff too, to no avail with version 3.0.0). Also note that it is initialized as a global variable within that file (should it matter).

and then checks for the saved data.
I tried, right after the connection, to print out the saved data, and the result was "null". As it is, the app then proceeds to ask the server for that user's data and download/save it offline.
I tried killing the server and starting it again, forcing the app to reconnect to it (without hot reloading the app itself). The data stored was retrieved successfully this time: [18, 96, 332, 210, 3, Test] (it's a List < dynamic > )
So the problem seems to be only between app loads, as localstorage 3.0.0 is correctly handling stuff while the app is open. Not sure where I can find the file that should contain the data, but if you tell me I can look into it on my device and see if it gets written or not.
I should also note that I'm never calling the dispose method on the localstorage instance, because it is used everywhere within the app. I checked and you're not doing it either on your demo app, so it might be of no concern.

**Comment by Maclaon** [comment]
@lesnitsky sorry, my mistake! the code snippet is very simple~
```
  static final LocalStorage localStorage = LocalStorage('app_data.json');
  static final User user = User.fromJson(localStorage.getItem('user'));

  static Future<void> initPlatformState() async {
    localStorage.stream.forEach((element) {print('see u: ' + element.toString());});
    localStorage.setItem('filter_movies', ['1',2,3]);
    try {
      if (Platform.isAndroid) {
        deviceData = _readAndroidBuildData(await deviceInfoPlugin.androidInfo);
      } else if (Platform.isIOS) {
        deviceData = _readIosDeviceInfo(await deviceInfoPlugin.iosInfo);
      }
    } on PlatformException {
      deviceData = <String, dynamic>{
        'Error:': 'Failed to get platform version.'
      };
    }
  }
```
but, it will not persist anything when i restart my app! each time it looks like a new `localStorage`!

**Comment by Maclaon** [comment]
@lesnitsky can u take a glance at this issue?

**Comment by lesnitsky** [comment]
@Maclaon can you wrap `localStorage.setItem` with try catch and also add `await` before?
```diff
- localStorage.setItem('filter_movies', ['1',2,3]);
+ try {
+   await localStorage.setItem('filter_movies', ['1',2,3]);
+ } catch (err) {
+   print(err);
+ }
```

**Comment by sotisoti** [comment]
@lesnitsky ,

I try the example it works but if I try to get the items via initState() it's always null:

```
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'package:localstorage/localstorage.dart';

void main() {
  if (!kIsWeb && Platform.isMacOS) {
    debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
  }

  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Localstorage Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  HomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class TodoItem {
  String title;
  bool done;

  TodoItem({this.title, this.done});

  toJSONEncodable() {
    Map<String, dynamic> m = new Map();

    m['title'] = title;
    m['done'] = done;

    return m;
  }
}

class TodoList {
  List<TodoItem> items;

  TodoList() {
    items = new List();
  }

  toJSONEncodable() {
    return items.map((item) {
      return item.toJSONEncodable();
    }).toList();
  }
}

class _MyHomePageState extends State<HomePage> {
  final TodoList list = new TodoList();
  final LocalStorage storage = new LocalStorage('todo_app');
  bool initialized = false;
  TextEditingController controller = new TextEditingController();

  void initState() {
    print('initState');
    print('===========================================');
    var items = storage.getItem('todos');
    print(items);
    print('===========================================');
    super.initState();
  }

  _toggleItem(TodoItem item) {
    setState(() {
      item.done = !item.done;
      _saveToStorage();
    });
  }

  _addItem(String title) {
    setState(() {
      final item = new TodoItem(title: title, done: false);
      list.items.add(item);
      _saveToStorage();
    });
  }

  _saveToStorage() {
    storage.setItem('todos', list.toJSONEncodable());
  }

  _clearStorage() async {
    await storage.clear();

    setState(() {
      list.items = storage.getItem('todos') ?? [];
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Localstorage demo'),
      ),
      body: Container(
          padding: EdgeInsets.all(10.0),
          constraints: BoxConstraints.expand(),
          child: FutureBuilder(
            future: storage.ready,
            builder: (BuildContext context, AsyncSnapshot snapshot) {
              if (snapshot.data == null) {
                return Center(
                  child: CircularProgressIndicator(),
                );
              }

              if (!initialized) {
                var items = storage.getItem('todos');

                if (items != null) {
                  list.items = List<TodoItem>.from(
                    (items as List).map(
                      (item) => TodoItem(
                        title: item['title'],
                        done: item['done'],
                      ),
                    ),
                  );
                }

                initialized = true;
              }

              List<Widget> widgets = list.items.map((item) {
                return CheckboxListTile(
                  value: item.done,
                  title: Text(item.title),
                  selected: item.done,
                  onChanged: (bool selected) {
                    _toggleItem(item);
                  },
                );
              }).toList();

              return Column(
                children: <Widget>[
                  Expanded(
                    flex: 1,
                    child: ListView(
                      children: widgets,
                      itemExtent: 50.0,
                    ),
                  ),
                  ListTile(
                    title: TextField(
                      controller: controller,
                      decoration: InputDecoration(
                        labelText: 'What to do?',
                      ),
                      onEditingComplete: _save,
                    ),
                    trailing: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: <Widget>[
                        IconButton(
                          icon: Icon(Icons.save),
                          onPressed: _save,
                          tooltip: 'Save',
                        ),
                        IconButton(
                          icon: Icon(Icons.delete),
                          onPressed: _clearStorage,
                          tooltip: 'Clear storage',
                        )
                      ],
                    ),
                  ),
                ],
              );
            },
          )),
    );
  }

  void _save() {
    _addItem(controller.value.text);
    controller.clear();
  }
}
```

**Comment by wfe8006** [comment]
@lesnitsky's snippet in
https://github.com/lesnitsky/flutter_localstorage/blob/master/example/lib/main.dart#L109-L119
definitely helped me fix the issue. Calling getItem in `FutureBuilder(future: storage.ready` works now

**Comment by nicoroy2561** [comment]
Any way to do this outside of future builder? I mean, is there any way it
can be integrated to the the storage.getItem call if called with await,
rather than having it return a null value if it takes too long to
initialize the library itself?
Seems rather akward having to create a separate method that one can call
and await upon to make sure it's been initialized, if it's as common as it
appears to be.

To be clear, I'm a big fan of getItem not being async, but if that means I
might get null even when a variable is set, is rather go with the async
version.

2020年6月1日(月) 午後5:23 sotisoti <notifications@github.com>:

**Comment by lesnitsky** [comment]
localstorage initialization is asynchronous (since you have to read the contents of your storage from disk), that's why you should subscribe to `ready` and perform any reads/writes only after storage was initialized.

**Comment by nicoroy2561** [comment]
I managed to get v3.0.0 working by awaiting on its readiness before fetching / updating data, so using a FutureBuilder or simply await should fix this. Apparently they changed something within the latest stable flutter update, as even v2.0.0 I had been using thus far wouldn't be loaded properly any longer now.
Anyway, as it seems to work fine now, I'll go ahead and close this.
thank you @lesnitsky for the support.
