### ISSUE TITLE
Method to obtain all items from storage?

### ISSUE THREAD

**Issue by RadovanF** [lesnitsky/flutter_localstorage#39]
Hello,

may I ask you, is there any way how to obtain all items from localstorage? I would like to create storage with different random generated id for each item. Fro example: 
storage.setItem("a512aa", list.toJSONEncodable()); 
storage.setItem("b560bb", list.toJSONEncodable()); 
storage.setItem("c987cc", list.toJSONEncodable()); 
...
However, when I do it, I cannot access individual items using getItem("key"), since I do not store IDs when the app is closed. So the method getAllItems can solve this problem. Is it possible to delete individual item based on key?

Or do I something wrong?

Thanks

EDIT: I solve It with the second storage that is reserved for object IDs only. Issue can be closed, Thanks :)

**Comment by lesnitsky** [comment]
@midwej the only way to do this is to keep track of ids under a separate key. I'd recommend something like this:

```dart
final ids = list.map((item) => item.id).toList();
localStorage.setItem('_ids', ids);

list.forEach((item) => localStorage.setItem(item.id, item.toJson()));
```
