### ISSUE TITLE
Store into External Storage

### ISSUE THREAD

**Issue by spidgorny** [lesnitsky/flutter_localstorage#4]
Current version stores data into /data folder which is not easily accessible.
Would be nice to be able to save into external storage (sd card).

**Comment by lesnitsky** [comment]
@spidgorny Any suggestions on API?

**Comment by spidgorny** [comment]
How about ``getExternalStorageDirectory()`` from ``path_provider``?
No support for iOS - I know, then fall back to ``getApplicationDocumentsDirectory()``.

@see https://github.com/flutter/plugins/blob/master/packages/path_provider/lib/path_provider.dart#L61

**Comment by lesnitsky** [comment]
@spidgorny I meant localstorage api. I think it's better to leave a choice for package users, rather than just changing file location internally.
How about

```js
new LocalStorage(key, path)
```

so that users could specify location themselves (using path_provider API directly)

**Comment by spidgorny** [comment]
Yes, that sounds even better.
