### ISSUE TITLE
Nested JSON support?

### ISSUE THREAD

**Issue by 7arfoush** [lesnitsky/flutter_localstorage#42]
I was wondering if there is already a method to read/write nested JSON, and if not, can it be added?

**Comment by lesnitsky** [comment]
@7arfoush could you please expand the description of your feature request? I'm not sure if I understand it correctly

**Comment by 7arfoush** [comment]
For example, if I have the following JSON object:
`myObj = {
  "name":"John",
  "age":30,
  "cars": {
    "car1":"Ford",
    "car2":"BMW",
    "car3":"Fiat"
  }
 }`

Is there a way to access keys inside 'cars' and their values? If not, maybe there can be something like:
`Map<String, dynamic> data = storage.getItem('cars')[car1];`

If there are further nesting, it can be accessed in the same way:
`storage.getItem('cars')[car1][parts]...;`

I hope I clarified it enough. Tell me what you think.

**Comment by lesnitsky** [comment]
```dart
final data = storage.getItem('user') // { "name": "John" ... }
final cars = data['cars'];
final ford = cars['car1'];
```

alternatively, you can use [deep_map](https://pub.dev/packages/deep_map`) package

```dart
final data = storage.getItem('user');
final car = data.getDeep('cars.car1')
```

Answering your question related to the API extension: it's unlikely to have this kind of functionality. It repliacates the API of the [browser localstorage](https://developer.mozilla.org/ru/docs/Web/API/Window/localStorage).
\+ this feature is fairly straightforward to implement, so feel free to build your own package on top of localstorage 😉
