### ISSUE TITLE
localstorage returns null on getItem

### ISSUE THREAD

**Issue by ksydex** [lesnitsky/flutter_localstorage#48]
I want to init store with value from localstorage, but it always return null there.
Then I tried to getItem from localstorage in widget with this code:
`print('from local storage: '+localStorage.getItem('user').toString());`
And i get next output:
```
Performing hot restart...
Syncing files to device sdk gphone x86 arm...
Restarted application in 936ms.
I/flutter ( 4982): from local storage: null
I/flutter ( 4982): from local storage: {socialAccounts: [], culture: {key: en}, currency: {key: RUB}, id: 6, email: ..... } 
```
So, it is being called two times, where first returns null and second - actual value. 
What's the problem?

**Comment by lesnitsky** [comment]
make sure to `await storage.ready` before calling `getItem`

**Comment by ksydex** [comment]
@lesnitsky Yes, this worked. Would be good to mention what `await storage.ready` is actually doing to prevent issues like this :)
 Thank you!
