### ISSUE TITLE
Localstorage doesn't persist when app is closed or restarted

### ISSUE THREAD

**Issue by gorebang** [lesnitsky/flutter_localstorage#49]
Unlike Shared_Prefs, when an app using localstorage is hot restarted or the app is closed on the device and restarted, data isn't persisted.

This can be seen by running the example solution, adding some todo items then performing a hot restart (SHIFT R)... the items won't be persisted.

Perhaps I misunderstood the purpose of the package; I was hoping to use it to persist JSON blobs on the device to be retrieved over a longer period of time.

**Comment by lesnitsky** [comment]
@gorebang hot restart works for me on all platforms

**Comment by pablofridman** [comment]
Same problem here, solved adding a setState()  before retrieving  the first time an element from the database (xxx.getItem('')).  Happens when you call getItem before finish rendering the app the first time in my case.....

**Comment by lesnitsky** [comment]
could you please make sure you wait for the localstorage to be initialized

```dart
storage.getItem('item'); // null if not yet initialized

await storage.ready;
storage.getItem('item'); // should return data
```

**Comment by lesnitsky** [comment]
Seems like https://github.com/lesnitsky/flutter_localstorage/issues/49#issuecomment-676146168 is the reason
