### ISSUE TITLE
NoSuchMethodError: The method 'lock' was called on null.

### ISSUE THREAD

**Issue by Stevensie95** [lesnitsky/flutter_localstorage#57]
This issue again on version ^3.0.6

I/flutter (20717): NoSuchMethodError: The method 'lock' was called on null.
I/flutter (20717): Receiver: null
I/flutter (20717): Tried calling: lock()

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.14.6 18G103 darwin-x64, locale zh-Hans-MY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by lesnitsky** [comment]
@Stevensie95 did it happen after calling `getItem` or `setItem`?

**Comment by Stevensie95** [comment]
No, it unable to setItem and getItem

**Comment by djaldave** [comment]
the get method when call

**Comment by midnightcigarettes** [comment]
I've encountered the same problem too. With this small snippet:

```
Future<void> main() async {
  LocalStorage storage = LocalStorage('test');
  await storage.ready;
  storage.setItem('test', 'a');
}
```

Version: localstorage: ^3.0.6+9

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.5 at F:\Windows\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)  
    • Android SDK at F:\Windows\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = F:\Windows\android-sdk
    • Java binary at: F:\Windows\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at F:\Windows\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

**Comment by lesnitsky** [comment]
make sure that:
1. you're calling `await storage.ready`
2. not using LocalStorage outside of widget tree (e.g. in `main`. LocalStorage requires flutter to be ready for platform calls. @midnight-cigarettes, that's your case)

Please confirm you're experiencing this issue and neither of the cases above is applicable to you

**Comment by ad-on-is** [comment]
Just add `WidgetsFlutterBinding.ensureInitialized();` in your main.

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  LocalStorage storage = LocalStorage('test');
  await storage.ready;
  storage.setItem('test', 'a');
}
```

**Comment by lexxxel** [comment]
I got the same Error:

```
Error:\n\nNoSuchMethodError: The method 'lock' was called on null.
Receiver: null
Tried calling: lock()\n\nStacktrace:
dart:core                                         Object.noSuchMethod
package:localstorage/src/directory/io.dart 48:25  DirUtils.flush
package:localstorage/localstorage.dart 102:18     LocalStorage._flush
package:localstorage/localstorage.dart 85:12      LocalStorage.setItem
===== asynchronous gap ===========================
dart:async                                        _asyncErrorWrapperHelper
package:localstorage/localstorage.dart 85:12      LocalStorage.setItem
===== asynchronous gap ===========================
dart:async                                        _asyncThenWrapperHelper
package:production/model/EventManager.dart 57:14  EventManager.saveEventsToLocal
===== asynchronous gap ===========================
dart:async                                        _asyncThenWrapperHelper
model/EventManager_test.dart 59:21                main.<fn>.<fn>
model/EventManager_test.dart 47:45                main.<fn>.<fn>
```
``` dart
---- in unit test -----
      var manager = EventManager();
      WidgetsFlutterBinding.ensureInitialized();

      manager.addEvent(simpleEvent);
      manager.addEvent(simpleEvent2);

      await manager.saveEventsToLocal();
      manager = null;

      manager = EventManager();
      expect(() => manager.getEventById(simpleEvent.id), throwsException);
      await manager.loadEventsFromLocal();
      expect(manager.getEventById(simpleEvent.id), equals(simpleEvent));


----- with event manager -----

class EventManager {
  List<Event> _events = [];
  final LocalStorage _storage = new LocalStorage('LocalEventStorage.json');

  Future<void> saveEventsToLocal() async {
    await _storage.ready;
    _storage.setItem('EventList', _events);
  }

  Future<void> loadEventsFromLocal() async {
    await _storage.ready;
    _events = _storage.getItem('EventList');
  }
}

```

by the way I moved `WidgetsFlutterBinding.ensureInitialized();` around, but nothing changed.

**Comment by ad-on-is** [comment]
@lexxxel you don't need to move it around, it has to be the first call within the main function.

**Comment by lexxxel** [comment]
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
test("Local Event Storage and Restore", () async {
      // here i create simple event 1 and two
      var manager = EventManager();

      manager.addEvent(simpleEvent);
      manager.addEvent(simpleEvent2);

      await manager.saveEventsToLocal();
      manager = null;

      manager = EventManager();
      expect(() => manager.getEventById(simpleEvent.id), throwsException);
      await manager.loadEventsFromLocal();
      expect(manager.getEventById(simpleEvent.id), equals(simpleEvent));
  });
}
```
but I still get
```
  EventManager_test.dart: EventManager: Local Event Storage and Restore [E]                                                                                                                                 
  NoSuchMethodError: The method 'lock' was called on null.
  Receiver: null
  Tried calling: lock()
  dart:core                                         Object.noSuchMethod
  package:localstorage/src/directory/io.dart 48:25  DirUtils.flush
  package:localstorage/localstorage.dart 102:18     LocalStorage._flush
  package:localstorage/localstorage.dart 85:12      LocalStorage.setItem
  
00:05 +23 -1: Some tests failed.     
```

If I run this Unit test on a Windows machine, everything is fine. The log from the last comment was inside my CI docker container. The Error message here is from my native Linux installation.

I can debug, that
```dart
// in io.dart
@override
  Future<void> init([Map<String, dynamic> initialData]) async {
    _data = initialData ?? {};

    final f = await _getFile();
    final length = await f.length(); <<--- init never reaches this point

    if (length == 0) {
      return flush({});
    } else {
      await _readFile();
    }
  }
```

I reported this bug to the Flutter team https://github.com/flutter/flutter/issues/74392

**Comment by lexxxel** [comment]
I finally found the issue: You have to have the package `xdg-user-dirs` installed under Linux.

io.dart calls internally `getApplicationDocumentsDirectory` which failed on my system.
```dart
/// Gets the xdg user directory named by `dirName`.
///
/// Use [getUserDirectoryNames] to find out the list of available names.
Directory getUserDirectory(String dirName) {
  final ProcessResult result = _processManager.runSync(
    <String>['xdg-user-dir', dirName],
    includeParentEnvironment: true,
    stdoutEncoding: Encoding.getByName('utf8'),
  );
  final String path = utf8.decode(result.stdout).split('\n')[0];
  return Directory(path);
}
```
 I didn't check the result of `onError` that's why I missed that.

However, that means, that `xdg-user-dirs` is a dependency on Linux Systems!

**Comment by juanmanavarro** [comment]
@lexxxel i've got `xdg-user-dirs` installed but still doesn't work. Can you explain more detailed, please?

**Comment by lexxxel** [comment]
> @lexxxel i've got `xdg-user-dirs` installed but still doesn't work. Can you explain more detailed, please?

the LocalStorage has an `onError` member variable. You can check this Variable e.g.:
```dart
LocalStorage storage = new LocalStorage('LocalStorage.json');
storage.onError.addListener(() {
      print("LocalStorage:onError: ${_storage.onError.value}");
    });
```
then run your Test and have a look if something gets printed. In my case, I got PlatformNotSupportedError, or something like that. Have a look into flutter/flutter#74392 to read more about that issue. 
```

**Comment by juanmanavarro** [comment]
@lexxxel thank you.

**Comment by bahador-r** [comment]
same issue

**Comment by atishpaul** [comment]
Hi, Please try this.

````
final storage = new LocalStorage('config.json');

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await storage.ready;
  runApp(MyApp());
}
````

Now you can use it like

`await storage.setItem('favList',myList);`

`flutter clean` 

and a fresh installation of your application is must.

**Comment by maliaydemir** [comment]
Can you edit app level build.gradle like this. Just add `shrinkResources true` and `minifyEnabled false`.
```
buildTypes {
        release {
            shrinkResources false
            minifyEnabled false
        }
    }
```

**Comment by elihaidv** [comment]
I suggest to add this to README

**Comment by lesnitsky** [comment]
> Can you edit app level build.gradle like this. Just add `shrinkResources true` and `minifyEnabled false`.
> 
> ```
> buildTypes {
>         release {
>             shrinkResources false
>             minifyEnabled false
>         }
>     }
> ```

I doubt this has anything to do with the localstorage package. Those configs affect only native code, localstorage doesn't have anything in native. The only dependency it has is `path_provider`, so if the issue has something to do with wrong paths – that's an issue of `path_provider`
