### ISSUE TITLE
Support for dart 3.0 null-safety

### ISSUE THREAD

**Issue by ThijSlim** [lesnitsky/flutter_localstorage#65]

**Comment by thomasschwarzott** [comment]
I was just about to open this issue, too as I'm getting an error concerning the depending version of path_provider. I'll just add the error when trying to update my pubspec.yaml :)

```
Because localstorage 3.0.6+9 depends on path_provider ^1.6.14 and no versions of localstorage match >3.0.6+9 <4.0.0, localstorage ^3.0.6+9 requires path_provider ^1.6.14.

So, because [package_name] depends on both localstorage ^3.0.6+9 and path_provider ^2.0.1, version solving failed.
```

**Comment by Ali-Fadaei** [comment]
@thomasschwarzott change path_provider ^1.6.14 to path_provider: ^2.0.1 manually! it's working

**Comment by thomasschwarzott** [comment]
@Ali-Fadaei indeed - but the package should be up to date and working automatically on install :) 

Edit: there is actually a pull request already: https://github.com/lesnitsky/flutter_localstorage/pull/66

**Comment by tcd93** [comment]
Oops didn't see #66 

I refactored to dart 2, did some preliminary checks and seems to work, guys please help test #70  thanks

**Comment by adamontherun** [comment]
been using #70 for a few days and it works great @tcd93 @lesnitsky
