### ISSUE TITLE
Error: NoSuchMethodError: 'toJson'

### ISSUE THREAD

**Issue by moses-everette** [lesnitsky/flutter_localstorage#79]
I'm not sure why this magically began to appear. On **setItem(key, value)**, the debugger blows up and tells me that 'toJson' does not exist. However, data is still written to local storage. It is really odd.

**flutter doctor -v**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.59.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

C:\Users\everettem\Documents\cmms\server>flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.2.3 at C:\Users\everettem\Documents\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\everettem\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Users\everettem\Documents\jdk-11.0.2\bin\java.exe
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\everettem\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.67

**Comment by lesnitsky** [comment]
Could you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by moses-everette** [comment]
Yeah, apologies. I should have provided that. I believe this issue is only mine so you may be able to close this issue. However, in my case:

- Execute two network requests for validity of any stored credentials.
- On complete, check to see if the response was satisfactory and update state.
- If fail, the **setItem(key, value)** yields NoSuchMethodError. Peeking into the function, there is a null check on the body parameter. However, the information I am trying to write is not null itself. What I see in local storage is exactly what I expect to see there.


`
authenticatingUser.then((value) {
      setState(() {
          authenticatedUser = value.statusCode == 200;
      });
});
`

**Comment by moses-everette** [comment]
So I believe this issue isn't the library itself. I think the issue lies within some problem with the flutter toolset itself. My issue boiled to some failed state change after a network request. The logic follows as is:

- Request from the server the validity of some possibly stored credentials
- If pass, navigate to another screen. If fail, request the user to enter credentials.
- Check again with newly entered credentials. If pass, store some stuff in local storage for automated login. This is where the error appears upon using **setItem(key, value)**

Not sure adding code helps this situation out at all, as I'm not running into nulls (that I'm aware of). And everything I expect to be written to local storage is there. I think it had to do with a race condition between two futures (currently my auth is two-stage. I might just reduce to single-stage authentication). Embedding the second callback into the first appears to have fixed the issue. So maybe this is my fault, but might be worth reporting here incase there is something that helps you!

**Comment by moses-everette** [comment]
Actually, you can close this. This is because I mistakenly did not wait for the storage to be ready. Newb move. Newb. Move.
