### ISSUE TITLE
[announcement] persistent queue package on pub built on top of flutter_localstorage!

### ISSUE THREAD

**Issue by oakromulo** [lesnitsky/flutter_localstorage#8]
https://pub.dartlang.org/packages/flutter_persistent_queue

**Comment by lesnitsky** [comment]
@oakromulo Cool stuff 👍 We probably have a use case for this package in our own app 🤔

**Comment by oakromulo** [comment]
That's truly awesome. Thank you very much for publishing **flutter_localstorage**!
