### ISSUE TITLE
keys

### ISSUE THREAD

**Issue by JanRegent** [lesnitsky/flutter_localstorage#80]
It's posible to add keys property that return all keys?
Thanks a lot.

**Comment by lesnitsky** [comment]
check out [this comment](https://github.com/lesnitsky/flutter_localstorage/issues/39#issuecomment-615258176)

This package tries have feature parity with [this standard](https://html.spec.whatwg.org/multipage/webstorage.html#storage-2) which doesn't mention `keys` as a property
