### ISSUE TITLE
Files are in user's Documents on desktop

### ISSUE THREAD

**Issue by ostpnk** [lesnitsky/flutter_localstorage#83]
On desktop, files containing data being put into user's Documents directory and make a mess in it..
(on Linux: /home/username/Documents )

Instead of using getApplicationDocumentsDirectory() of path_provider in /lib/src/directory/io.dart, 
getApplicationSupportDirectory() of path_provider should be used.

**Comment by lesnitsky** [comment]
You can pass the application support directory as a second argument of the `LocalStorage` constructor

```dart
final dir = await getApplicationSupportDirectory();
final storage = LocalStorage('appstorage', dir.path)
```
