### ISSUE TITLE
Very good library，But I have a question

### ISSUE THREAD

**Issue by 390057892** [lesnitsky/flutter_localstorage#85]
What is the principle of file reading and writing implementation? I don't see you using methodchannel

**Comment by hellohejinyu** [comment]
https://github.com/lesnitsky/flutter_localstorage/blob/14b55c3c67575abf99d3b8dc34d4399dfb66436d/lib/src/directory/io.dart#L96-L112

https://github.com/lesnitsky/flutter_localstorage/blob/14b55c3c67575abf99d3b8dc34d4399dfb66436d/lib/src/directory/web.dart#L12

**Comment by lesnitsky** [comment]
that's correct answer
