### ISSUE TITLE
Inconsistent Return Format

### ISSUE THREAD

**Issue by waltmoorhouse** [lesnitsky/flutter_localstorage#9]
When I store an object, let's call it MyObject, which is serializable to JSON, using storage.setItem(key, _myObject) then a few seconds later I retrieve it using storage.getItem(key), I get an instance of MyObject back.  When I then close the app and reopen it, where I do storage.getItem(key) I get back the JSON Map<String, dynamic> instead of the Object.  The return should either always be JSON, or should require a class parameter so that it can always be the Object class passed in.

**Comment by lesnitsky** [comment]
@waltmoorhouse thanks for bringing this up
This is totally valid issue
What behavior seems more intuitive in your opinion?

**Comment by rodydavis** [comment]
What i do to get around this is something like this:

``` dart
final contacts = List?.from(storage.getItem('contacts') ?? [])
      ?.map((i) => i is ContactRow ? i : ContactRow.fromJson(i))
      ?.toList();
```

**Comment by rodydavis** [comment]
But I agree is should probably always be JSON returning.

**Comment by waltmoorhouse** [comment]
I think always giving back JSON is fine.

**Comment by rodydavis** [comment]
@lesnitsky Thanks for the latest update!
