### ISSUE TITLE
I cant find the file i created in the app folder

### ISSUE THREAD

**Issue by jwiemann** [lesnitsky/flutter_localstorage#90]
I stored a file with your flutter SDK and it worked as expected.
But now I'm trying to get this file from a native app. And somehow I cant find the file, even if my app has the same unique app name and a higher version number.

Where does this Package store it's files?

Thank you very much!

**Comment by lenlo** [comment]
The default directory for the package's files is the app's Documents directory, as returned by path_provider's `getApplicationDocumentsDirectory()` function. Still, it would be helpful if the package had a method that returned the full path for a store's underlying file as you may need to access it directly after using it, e.g. to rename it or to delete it when it's no longer needed.

**Comment by lesnitsky** [comment]
Storage file could be locatied in the application document directory. File name is `storage-61f76cb0-842b-4318-a644-e245f50a0b5a.json`.

Here's a simple script that will log the location of the storage file:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final dir = await getApplicationDocumentsDirectory();
  final path = p.join(
    dir.path,
    'storage-61f76cb0-842b-4318-a644-e245f50a0b5a.json',
  );

  print('Storage location: $path');
}
```
