### ISSUE TITLE
Unhandled Exception: FileSystemException: File closed

### ISSUE THREAD

**Issue by mixable** [lesnitsky/flutter_localstorage#94]
I want to use LocalStorage with different files (keys). Each of the files is opened with `LocaleStorage('my_file.ext')`. I always open only one file, there are not multiple files open at the same time.

When working on Windows, I have to call the `dispose()` method to close a file before opening another. This is necessary to release the file handle. This works as expected, calling `dispose()` before opening another file will release the file handle. If `dispose()` is not called, the file cannot be edited or deleted until the app is closed.

When opening the same file again, LocalStorage uses the file instance stored in `_cache` map. As the file handler has been disposed, the following exception is thrown:
```
Unhandled Exception: FileSystemException: File closed, path = '...'
```

To make this work, it is necessary to remove the instance from `_cache`, when calling `dispose()`. Otherwise it's not possible to read or write the same file later. This is also a problem when you handle files with the same name but in different paths.

**Comment by srolemberg** [comment]
Im over the same problem here. Im switching screens and saving some data with 3 files names.

They works normal over the frist run, but fails after a secong load of any of them.
