### ISSUE TITLE
it doesn't persist the data in flutter web even if i don't close the browser.

### ISSUE THREAD

**Issue by MarceloDiefenbach** [lesnitsky/flutter_localstorage#95]
I'm saving a variable that I need to access even if the user accesses the web application another day. but the saved variable is not persisting.

I can retrieve a saved variable if I don't rebuild the application, but when I rebuild the data no longer exists

**Comment by rirjkl19** [comment]
This is also happening on my end

**Comment by Andrewcpu** [comment]
Same issue on my end (MacOS)

**Comment by WillBeebe** [comment]
Same here

**Comment by lesnitsky** [comment]
please upgrade to the latest version.
