### ISSUE TITLE
Converting object to an encodable object failed: _Map len:1

### ISSUE THREAD

**Issue by YawarOsman** [lesnitsky/flutter_localstorage#97]
i tried to save this map with the package but i found that issue, it's the same this in Shared Preferences too.

this is my map:
{1: [{id: null, item: {id: 100, name: Falafel sandwich 1, price: 1000.0, status: active, category: {id: 2, name: Shawrma}, imageId: XXXXXXXX, dateTime: 2023-02-09 09:43:26.000}, invoice: null, price: 1000.0, quantity: 1}, {id: null, item: {id: 99, name: Hot Chocolate 3hazar, price: 3000.0, status: active, category: {id: 9, name: Hot Drinks}, imageId: XXXXXXXX, dateTime: 2023-02-09 09:40:23.000}, invoice: null, price: 3000.0, quantity: 3}]}

**Comment by TimeLord2010** [comment]
Did you find the cause to the issue?
