### ISSUE TITLE
Simple string saving throws error that toJson() not found in String.

### ISSUE THREAD

**Issue by zulkarnainshah** [lesnitsky/flutter_localstorage#99]

**Comment by lesnitsky** [comment]
Can't reproduce, the code below works as expected

```dart
import 'package:localstorage/localstorage.dart';

Future<void> main() async {
  final storage = LocalStorage('strings');
  await storage.ready;

  final firstLaunch = storage.getItem('firstLaunch') ?? true;

  if (firstLaunch) {
    await storage.setItem('firstLaunch', false);
    await storage.setItem('key', 'value');
  } else {
    print(storage.getItem('key'));
  }
}
```

**Comment by zulkarnainshah** [comment]
@lesnitsky  If you keep the **All Exceptions** breakpoint checked in debugger, you will see the error. Attaching screenshot of the error when caught at runtime. The passed value **selectedDateFilter.value** is a string in the screenshot.
![Screenshot 2023-04-07 at 7 12 34 AM](https://user-images.githubusercontent.com/12382340/230523590-07b315d4-1f9c-452a-9143-82efc30c6f5a.png)

**Comment by lesnitsky** [comment]
`All exceptions` shows even properly handled ones, this is the case, see [here](https://github.com/lesnitsky/flutter_localstorage/blob/master/lib/localstorage.dart#L78)

**Comment by zulkarnainshah** [comment]
So are we doing anything wrong? Is there a way to fix?

**Comment by lesnitsky** [comment]
There's nothing wrong in throwing an exception and handling it in `catch`. The string you're trying to save is actually there and you should be able to read it back with `getItem`
